---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200

  tasks:
  - name: ensure apache is at the latest version
    yum: pkg=httpd state=latest
  - name: replace default index.html file
    copy: src=/static_files/index.html dest=/var/www/html/ mode=0644
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - name: add services to firewalld service
    firewalld:
    service: http
    permanent: yes
    state: enabled
  - firewalld:
    service: https
    permanent: yes
    state: enabled
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
      
