---
- hosts: all

  tasks:
  - name: yum install epel
    yum: name=epel-release.noarch state=latest

  - name: download remi repo rpm
    get_url: url=http://rpms.remirepo.net/enterprise/7/remi/x86_64//php73-php-7.3.12-1.el7.remi.x86_64.rpm dest=/root/  
  - name: install remi repo rpm
    yum: name=/root/php73-php-7.3.12-1.el7.remi.x86_64.rpm state=present
 # - name: enable remi
   # yum-config-manager: enable=remi-php73

  - name: install php
    yum: name={{item}} state=installed
    with_items:  
      - php73
      - php-mysql
      - php-pdo
      - php73-gd
      - php73-mbstring
      - php73-fpm

  - name: Start php-fpm
    service: name=php-fpm state=started enabled=yes

  - name: restart nginx
    service:
      name: nginx
      state: restarted
