---
- hosts: all

  tasks:
  - name: yum install epel
    yum: name=epel-release.noarch state=latest

  - name: download remi repo rpm
    get_url: url=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm dest=/root/  
  - name: install remi repo rpm
    yum: name=/root/remi-release-7.rpm state=present
    yum-config-manager: name=remi-php72 state=--enable

  - name: install php
    yum: name={{item}} state=installed
    with_items:  
      - php
      - php-mysql
      - php-pdo
      - php-gd
      - php-mbstring
      - php-fpm

  - name: Start php-fpm
    service: name=php-fpm state=started enabled=yes

  - name: restart nginx
    service:
      name: nginx
      state: restarted
