---
- hosts: all
  tasks:
  - name: Ansible Insert multiple lines using blockinfile
    blockinfile:
      dest: /etc/yum.repos.d/MariaDB.repo
      block: |
        [mariadb]
        name = MariaDB
        baseurl = http://yum.mariadb.org/10.1/centos7-amd64
        gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck=1s
      backup: yes
  - name: install mariadb 10
    yum: name={{item}} state=installed
    with_items:
      - MariaDB-server 
      - MariaDB-client
    service: name=mariadb state=started enabled=yes
