---
- hosts: all

  tasks:
     - name: yum install epel
       yum: name=epel-release.noarch state=latest

     - name: install remi repo rpm
       yum: name=/root/remi-release-7.rpm state=present

      - name: install php
       yum: name={{item}} state=installed
       with_items:  
       - php
       - php-mysql
       - php-pdo
       - php-gd
       - php-mbstring
       - php-fpm

      - name: restart php-fpm
        service:
        name: php-fpm
        state: restarted
  
      - name: restart nginx
        service:
        name: nginx
        state: restarted
