---
- hosts: all

  tasks:
  - name: install php
      yum: name={{item}} state=installed
      with_items:  
      - php
      - php-mysql
      - php-pdo
      - php-gd
      - php-mbstring
      - php-fpm
      
  - name: copy file
      shell: echo "<?php phpinfo (); ?>" > /usr/share/nginx/html/info.php

  - name: install mariadb
      yum: name={{item}} state=installed
      with_items:
      - mariadb-server
      - mariadb
    
  - name: restart nginx
      service:
        name: nginx
        state: restarted
