---
- hosts: all
  tasks:

  - name: Delete database with name 'wordpress'
    mysql_db:
      name: wordpress
      state: absent

  - name: Create a new database with name 'wordpress'
    mysql_db:
      name: wordpress
      state: present

  - name: Create database user using hashed password with all database privileges
    mysql_user:
      name: wpuser
      password: wpuserpassword
      priv: 'wordpress.*:ALL,GRANT'
      state: present
