---
- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: /static_files/index.html
      dest: /usr/share/nginx/html/index.html
      
  - name: Insert nginx config file 
    template:
      src: /static_files/mynginxweb.local.conf
      dest: /etc/nginx/conf.d/mynginxweb.local.conf
      
  - name: Insert fastcgi config file 
    template:
      src: /static_files/fastcgi.conf
      dest: /etc/nginx/fastcgi.conf
      
  - name: Rename the default.conf file 
    copy: 
      remote_src: True 
      src: /etc/nginx/conf.d/default.conf 
      dest: /etc/nginx/conf.d/default.conf-backup
      
  - name: Remove old files default.conf
    file: 
      path: /etc/nginx/conf.d/default.conf 
      state: absent
  
  - name: define nginx as a user in php-fpm config file
    replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '(.*user = apache.*)'
      replace: 'user = nginx'
 
  - name: define nginx as a gorup in php-fpm config file     
    replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '(.*group = apache.*)'
      replace: 'group = nginx' 
      
  - name: config php.ini file
    lineinfile:
      path: /etc/php.ini
      insertafter: "(.*cgi.fix_pathinfo=.*)" 
      line: "cgi.fix_pathinfo=0"
      firstmatch: yes
      state: present 
    
  - name: Start NGiNX
    service:
      name: nginx
      state: started
      
  - name: Start php-fpm
    service:
      name: php-fpm
      state: started
