---
- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: /static_files/index.html
      dest: /usr/share/nginx/html/index.html
      
  - name: Insert config file 
    template:
      src: /static_files/mynginxweb.local.conf
      dest: /etc/nginx/conf.d/mynginxweb.local.conf
      
  - name: Rename the default.conf file 
    copy: 
      remote_src: True 
      src: /etc/nginx/conf.d/default.conf 
      dest: /etc/nginx/conf.d/default.conf-backup
      
  - name: Remove old files default.conf
    file: 
      path: /etc/nginx/conf.d/default.conf 
      state: absent
      
  - name: Start NGiNX
    service:
      name: nginx
      state: started
      
  - name: Start php-fpm
    service:
      name: php-fpm
      state: started
