---
- hosts: all
  tasks:
  - name: Install ntp
    yum:
      name: ntp
      state: latest
      
  - name: ensure ntp is running (and enable it at boot)
    service: name=ntpd state=started enabled=yes
    
  tasks:
  - name: Commenting default server config using the regualr expressions in Ansible.
    replace:
      path: /etc/ntp.conf
      regexp: '(.*centos.pool.ntp.org.*)'
      replace: '#\1'
  
  tasks:
  - name: "Example1: Validate if a String or line is present in the file"
    become: yes
    tags: lineinfilecentospool
    lineinfile:
      path: /etc/ntp.conf
      insertafter: "(.*3-centos.pool.ntp.org.*)" 
      line: "server 192.168.100.34 iburst"
      firstmatch: yes
      state: present  
      
   - name: Restart service httpd, in all cases
     service:
       name: ntpd
       state: restarted
