---
- hosts: all

  vars:
    ntp_server: "192.168.100.34"
    
  tasks:
  - name: Install ntp
    yum:
      name: ntp
      state: latest
      
  - lineinfile:
      path: /etc/ntp.conf
      regexp: '(.*centos.pool.ntp.org.*)'
      replace: '#\1'
  
  - lineinfile:
      path: /etc/ntp.conf
      insertafter: "^3-centos.pool.ntp.org+" 
      line: 'Server={{ ntp_server }} iburst'
      firstmatch: yes
      state: present
       
  - name: ensure ntp is running (and enable it at boot)
    service: name=ntpd state=started enabled=yes 
