---
- hosts: all

  
  tasks:
  - name: "Example1: Validate if a String or line is present in the file"
    become: yes
    tags: lineinfilecentospool
    lineinfile:
      path: /etc/ntp.conf
      insertafter: "(.*3-centos.pool.ntp.org.*)" 
      line: "server 192.168.100.34 iburst"
      firstmatch: yes
      state: present  
      
  - name: Restart service httpd, in all cases
    service:
      name: ntpd
      state: restarted
