---
- hosts: all
  tasks:
  - name: Install ntp
    yum:
      name: ntp
      state: latest
      
  - name: ensure ntp is running (and enable it at boot)
    service: name=ntpd state=started enabled=yes
