---
- name: Install NTP
  hosts: all  
  vars:
    ntp_server: "192.168.100.34"
    
  tasks:
  - name: Install ntp
    yum:
      name: ntp
      state: latest
      
  - replace:
      path: /etc/ntp.conf
      regexp: '(.*centos.pool.ntp.org.*)'
      replace: '#\1'
  
  - lineinfile:
      path: /etc/ntp.conf
      insertafter: "(.*3.centos.pool.ntp.org.*)" 
      line: "server 192.168.100.34 iburst"
      firstmatch: yes
      state: present
       
  - name: ensure ntp is running (and enable it at boot)
    service: name=ntpd state=started enabled=yes 
    
  - name: add port to firewalld service
    firewalld:
    source: 192.168.100.34/32
    permanent: yes
    state: enabled/
  - name: firewalld reload
    command: firewall-cmd --reload
