---
- name: Install NTP
  hosts: all  
  vars:
    ntp_server: "XXX.XXX.XXX.XXX"
    
  tasks:
  - name: Install ntp
    yum:
      name: ntp
      state: latest
      
  - replace:
      path: /etc/ntp.conf
      regexp: '(.*centos.pool.ntp.org.*)'
      replace: '#\1'
  
  - lineinfile:
      path: /etc/ntp.conf
      insertafter: "(.*3.centos.pool.ntp.org.*)" 
      line: "server XXX.XXX.XXX.XXX iburst"
      firstmatch: yes
      state: present
       
  - name: ensure ntp is running (and enable it at boot)
    service: name=ntpd state=started enabled=yes 

  - name: add service to firewalld service
    firewalld:
      service: ntp
      permanent: yes
      state: enabled
  - name: firewalld reload
    command: firewall-cmd --reload
