---
- hosts: all
tasks:
- name: Install updates 
  yum:
    name: "*"
    state: latest
 
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
     policy: targeted
     state: permissive
