---
- hosts: all

  vars:
    zabbix_server: "192.168.100.70"

  tasks:
  - name: install epel repo
    yum: name=epel-release state=latest

  - name: Installing the Zabbix Agent
    yum: name=zabbix-agent state=latest

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^LogFileSize=0'
      line: 'LogFileSize=256'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# EnableRemoteCommands=0'
      line: 'EnableRemoteCommands=1'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server=127.0.0.1'
      line: 'Server={{ zabbix_server }}'

#  - lineinfile:
#      path: /etc/zabbix/zabbix_agentd.conf
#      regexp: '^ServerActive=127.0.0.1'
#      line: 'ServerActive={{ zabbix_server }}'

 # - lineinfile:
 #     path: /etc/zabbix/zabbix_agentd.conf
 #     regexp: '^Hostname=Zabbix server'
 #     line: 'Hostname={{ ansible_hostname }}'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# Timeout=3'
      line: 'Timeout=3'

  - name: Starting the Zabbix Agent
    service: name=zabbix-agent state=started enabled=yes
