---
- hosts: all

  vars:
    zabbix_server: "XXX.XXX.XXX.XXX"

  tasks:
  
  - name: install the zabbiz-agent rpm from a remote repo
    yum:
      #name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
      name: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-agent-4.4.1-1.el7.x86_64.rpm
      state: present


  - name: Installing the Zabbix Agent
    yum: name=zabbix-agent state=latest

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^LogFileSize=0'
      line: 'LogFileSize=256'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# EnableRemoteCommands=0'
      line: 'EnableRemoteCommands=1'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server=127.0.0.1'
      line: 'Server={{ zabbix_server }}'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# Timeout=3'
      line: 'Timeout=3'

  - name: Starting the Zabbix Agent
    service: name=zabbix-agent state=started enabled=yes

  - name: add port to firewalld service
    firewalld:
      port: 10050/tcp
      permanent: yes
      state: enabled
  - name: firewalld reload
    command: firewall-cmd --reload
